spring:
  application:
    name: helloconsumer
server:
  port: 7211
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
helloprovider:
  ribbon:
    NIWSServerListClassName: org.apache.servicecomb.springboot.starter.discovery.ServiceCombServerList
cse:
  credentials:
    project: cn-north-1